task3
lina1812/TestGuru pull request #3
Opened 2021-03-19 13:22 UTC by lina1812

Создайте набор начальных данных для всех существующих моделей в файле db/seeds.rb

Создайте инстанс-метод в модели User, который принимает в качестве аргумента значение уровня сложности и возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности

Создайте метод класса в модели Test, который возвращает отсортированный по убыванию массив названий всех Тестов у которых Категория называется определённым образом (название категории передается в метод в качестве аргумента).

2021-03-19 15:55 UTC, VidgarVii requested changes

2021-03-19 15:55 UTC, VidgarVii commented on app/models/test.rb
> +    joins(:category).where(categories: { title: category_name }).order(title: :desc).pluck(:title)
в этом задании нужно все решать через SQL, с помощью  ActiveRecord queries, но без использования ассоциаций
суть урока - понять какую работу делает за нас `ActiveRecord` и для этого нужно здесь выполнить ее самому
давай сделаем следующее:
- избавься от ассоциаций (оставь связи только на уровне БД, но не на уровне моделей)
- перепиши методы в моделях `User`, `Test` без использования ассоциаций

2021-03-19 15:55 UTC, VidgarVii commented on db/seeds.rb
> +User.create([
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-03-19 15:55 UTC, VidgarVii commented on db/seeds.rb
> +              { name: 'Andrey', password: 'password', role: 'user' }
По моему я уже писал в прошлом ревью, что поле role лишние

2021-03-19 15:55 UTC, VidgarVii commented on db/seeds.rb
> +              { title: 'SSL', level: 1, category: Category.where(title: 'Database').first }
у тебя каждый раз происходит запрос в БД ждя получения данных. Такой сид будет проходить долго. И это оверхед. метод create тебе вернёт коллекцию объектов. Вот их и используй

2021-03-19 15:55 UTC, VidgarVii commented on app/models/user.rb
> +  end
1 ассоциации объявлены не верно и не полностью. 
2 В этом ДЗ нет задания объявлять связи на уровне моделей. Только в БД. Ассоциации будут далее по уроку
3 Тут так же надо использовать join, where как и в модели тестов

2021-03-19 21:12 UTC, lina1812 commented on app/models/test.rb
> +    joins(:category).where(categories: { title: category_name }).order(title: :desc).pluck(:title)
Ассоциации есть часть ActiveRecord и это большая часть работы которую он делает за нас. Генератор моделей автоматически создает ассоциации belongs_to при использовании поля :references,  а что это за строка написано в гайде который есть в дополнительных материалах к уроку. Но переделала как написал

2021-03-19 21:14 UTC, lina1812 commented on db/seeds.rb
> +              { name: 'Andrey', password: 'password', role: 'user' }
Это было про другое поле у вопроса. Его я уже удалила

2021-03-19 21:21 UTC, lina1812 commented on app/models/user.rb
> +  end
1. Запросы работали, поэтому считаю говорить, что ассоциации написаны не верно - не корректно.
2. В ДЗ нет указания как и с помощью чего писать запросы
3. Мне кажется один запрос в базу лучше 2х. join ни в чем не виноват. Where от хэша это магия ActiveRecord, а как писать запросы на SQL было в другой домашке, поэтому решила использовать такой подход

2021-03-19 21:27 UTC, lina1812 commented on db/seeds.rb
> +User.create([
Исправила

2021-03-21 07:42 UTC, VidgarVii requested changes

2021-03-21 07:42 UTC, VidgarVii commented on app/models/user.rb
> +  end
работает это еще не значит что корректно =)
Тут и в классе Test как раз таки и надо использовать запрос типа joins().where
Но в join следует в ручную с помощью sql связать таблицы. Т.е. без использования магии RoR
Должно быть понимание как это всё работает. Объединение таблиц с помощью чистого sql очень частый кейс в работе.

2021-03-21 07:42 UTC, VidgarVii commented on app/models/test.rb
> +  # belongs_to :category
комменты не относящиеся к ДЗ надо удалять

2021-03-21 07:42 UTC, VidgarVii commented on db/seeds.rb
> +                       { title: 'Ruby', level: 1, category: categories[1] },
без ассоциаций подобное (category: categories[1]) выражение работать не будет

2021-03-22 18:18 UTC, merged