add scope methods and validation
lina1812/TestGuru pull request #5
Opened 2021-03-24 20:38 UTC by lina1812

1. Определите scope-методы:
для выбора правильных Ответов
Для выбора Тестов по уровню сложности:
  простой (нулевой или первый уровень),
       средний (со второго по четвёртый),
       сложный (с пятого и выше). Значение положительной бесконечности можно получить с помощью константы Float::INFINITY
scope-метод по умолчанию для получения Категорий, отсортированных по названию в порядке возрастания

2. Используйте scope-методы вместо методов моделей, которые были определены в предыдущих заданиях

3. Определите валидации данных:
Наличие атрибутов title, body, email в соответствующих моделях
Уровень Теста может быть только положительным целым числом
Может существовать только один Тест с данным названием и уровнем
У одного Вопроса может быть от 1-го до 4-х ответов.

2021-03-25 06:37 UTC, VidgarVii requested changes

2021-03-25 06:37 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope { order(:title) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2021-03-25 06:37 UTC, VidgarVii commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
не очень понятно как валидация в модели Вопрос будет препятствовать созданию новых ответов в количестве больше 4... она же не будет вызываться, когда ты будешь добавлять новые ответы к вопросу - вызываются валидации того класса, объекты которого создаются

при создании нового объекта класса Ответ вызываются валидации класса Ответ, а не класса Вопрос

2021-03-25 06:37 UTC, VidgarVii commented on app/models/test.rb
> +  scope :hight_tests, -> { tests_by_level(HIGHT_LEVEL) }
1 Тавтология в названиях. И некорректный перевод.
Пример. У тебя вызов будет Test.light_tests. Лучше просто Test.light. Не надо повторять 2 раза имя. Люди так не общаются. И почему light? Мб всё таки easy или simple
2 Это тот случай когда 7 строк кода можно сократить в 3 У брав константы и tests_by_level

2021-03-25 06:37 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :author_tests, class_name: 'Test', inverse_of: :author, foreign_key: 'author_id', dependent: :nullify
foreign_key: :author_id

2021-03-26 11:18 UTC, VidgarVii requested changes

2021-03-26 11:18 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:number, "too much answers") unless Answer.where(question: question).count < 4
1 По возможности использовать IF предпочтительней чем Unless
2 данная проверка позволит создать 5 ответов

2021-03-26 12:19 UTC, lina1812 commented on app/models/answer.rb
> +    errors.add(:number, "too much answers") unless Answer.where(question: question).count < 4
1 Переписала на IF
2 Проверка не давала создать 5 ответ, ни при массовом создании, ни последовательно. Сейчас сделала обратное условие if Answer.where(question: question).count >= 4.

2021-03-26 20:34 UTC, VidgarVii commented on app/models/answer.rb
> +
нужен порядок в коде. Все валидации надо писать вместе. А скоупы ниже

2021-03-28 11:02 UTC, merged